name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository }}/web-app:latest -f web-app/Dockerfile web-app

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/web-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/web-app:latest
            docker stop web-app || true
            docker rm web-app || true
            docker run -d --name web-app -p 3000:3000 ghcr.io/${{ github.repository }}/web-app:latest

