name: CI/CD

on:
  push:
    branches: [main, features/compute-api]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ---- Deploy Python app directly to EC2 ----
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop existing application if running
            pkill -f "uvicorn" || true

            # Remove old application directory
            rm -rf /home/${{ secrets.EC2_USER }}/app

            # Create application directory
            mkdir -p /home/${{ secrets.EC2_USER }}/app

      - name: Copy application files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "rest-api/*"
          target: "/home/${{ secrets.EC2_USER }}/app/"
          strip_components: 1

      - name: Install dependencies and start application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/app

            # Install Python and pip if not available
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip python3-venv

            # Download uv

            # Create virtual environment
            source .venv/bin/activate

            # Install dependencies
            pip3 install --upgrade pip
            pip3 install --no-cache-dir uv
            uv sync --locked

            # Start the application in background
            nohup uv run fastapi dev --host 0.0.0.0 --port 8000 > app.log 2>&1 &

            # Wait a moment and check if the application started
            sleep 3
            if pgrep -f "uvicorn" > /dev/null; then
              echo "Application started successfully on port 8000"
            else
              echo "Failed to start application"
              cat app.log
              exit 1
            fi
