name: CI/CD

on:
  push:
    branches: [ main ]

# only one deploy runs at a time
concurrency:
  group: deploy-prod
  cancel-in-progress: false

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.tag.outputs.short_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: tag
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      # Build & push Next.js web app (npm only)
      - name: Build & push WEB (Next.js)
        uses: docker/build-push-action@v6
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-web:${{ steps.tag.outputs.short_sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build & push FastAPI backend
      - name: Build & push API (FastAPI)
        uses: docker/build-push-action@v6
        with:
          context: ./rest-api
          file: ./rest-api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-api:${{ steps.tag.outputs.short_sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
