name: CI/CD

on:
  push:
    branches: [main, features/compute-api]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # # Safer: stop only the uvicorn serving on our port, scoped to our user
      # - name: Prep remote
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       set -e
      #       pkill -u "$USER" -f "uvicorn .*--port 8000" || true
      #       rm -rf "$HOME/app"
      #       mkdir -p "$HOME/app"

      - name: Copy application files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # ** ensures directories and nested files are copied; also include dotfiles if needed
          source: "rest-api/**"
          target: "/home/${{ secrets.EC2_USER }}/app/"
          strip_components: 1

      - name: Install deps and start app (prod)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd "$HOME/app"
            sudo dnf update -y
            sudo dnf install -y python3

            python3 -m venv .venv
            . .venv/bin/activate
            python -m pip install --upgrade pip

            # If you use pyproject.toml + pip:
            # python -m pip install .

            # If you use requirements.txt:
            if [ -f requirements.txt ]; then
              python -m pip install -r requirements.txt
            fi

            # Start a production uvicorn (adjust module:app to your entry)
            # e.g., app/main.py with FastAPI() as "app" => app.main:app
            nohup .venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2 > app.log 2>&1 &

            sleep 3
            if pgrep -u "$USER" -f "uvicorn .*--port 8000" > /dev/null; then
              echo "Application started on port 8000"
            else
              echo "Failed to start application"
              tail -n 200 app.log || true
              exit 1
            fi
