name: CI/CD

on:
  push:
    branches: [main, features/docker]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---- Build and Push web-app ----
      # - name: Build web-app image
      #   run: |
      #     docker build --no-cache -t ghcr.io/${{ github.repository }}/web-app:latest -f web-app/Dockerfile web-app

      # - name: Push web-app image
      #   run: |
      #     docker push ghcr.io/${{ github.repository }}/web-app:latest

      # ---- Build and Push rest-api ----
      - name: Build rest-api image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository }}/rest-api:latest -f rest-api/Dockerfile rest-api

      - name: Push rest-api image
        run: |
          docker push ghcr.io/${{ github.repository }}/rest-api:latest

      # ---- Deploy to EC2 ----
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            whoami
            pwd
            docker pull ghcr.io/${{ github.repository }}/rest-api:latest

            docker stop rest-api || true && docker rm rest-api || true

            docker run -d --name rest-api -p 8080:8080 ghcr.io/${{ github.repository }}/rest-api:latest

          # commented out because we expose as 8080 on host
          # docker run -d --name rest-api -p 5000:5000 ghcr.io/${{ github.repository }}/rest-api:latest

      # removed web app deployment sections from 'Deploy to EC2'

      # docker pull ghcr.io/${{ github.repository }}/web-app:latest
      # docker stop web-app || true && docker rm web-app || true
      # docker run -d --name web-app -p 3000:3000 ghcr.io/${{ github.repository }}/web-app:latest
